### ISSUE TITLE
Should ORDER BY be prefixed in the returned value?

### ISSUE THREAD

**Issue by caub** [killercup/sortStringToSql#2]
so that:

```js
sortStringToSql('name') == 'ORDER BY name ASC NULLS LAST'
sortStringToSql('') ==  ''
sortStringToSql() ==  ''
```

**Comment by killercup** [comment]
No, I wouldn't do that. Outputting `ORDER BY` would prevent you from using this in a query builder, like <http://knexjs.org/#Builder-orderByRaw>.

- - -

I assume

```js
sortStringToSql('') ==  ''
sortStringToSql() ==  ''
```

already works? We might want to add some type checks to the code actually.

**Comment by caub** [comment]
I was doing 

```js
... query
${sortStringToSql(sort)} LIMIT $4 OFFSET $5
```
which doesn't work obviously, and must be something like 
```js
${sort ? 'ORDER BY '+sortStringToSql(sort) : ''} LIMIT $4 OFFSET $5
```
ok nvm since it's the format that expects knex, I'll deal with it

for me, using pg, it was making sense to do that (since other keywords like DESC.. are present in the returned value, it should be self-contained)

**Comment by killercup** [comment]
FYI, if you are using it this way in production, you should make sure to escape the input to `sortStringToSql` to not give user the ability to inject arbitrary sql.

**Comment by caub** [comment]
@killercup yes, right [discussed already](https://github.com/killercup/sortStringToSql/pull/1#issuecomment-298680703), I don't think it's easy to inject another SQL command since only words are allowed and then comma separated, the only issue is to allow columns that don't exists

I'll maybe just do:
`var re = /-?(foo|bar|bip)-?/g;` and a while with `re.exec(sortStr);`
